# Custom Language File for Launcher Customizer

[ejs.app]
title = "DotsMine Studio Launcher"

[ejs.landing]
mediaGitHubURL = " https://cafe.naver.com/duckamri"
mediaTwitterURL = "https://x.com/SeeGumChi"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/wkRhnByN2t"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "DotsMine Launcher"
welcomeDescription = "안녕하세요. 마인크래프트 서버/컨텐츠 제작 전문 DotsMine Studio입니다."
welcomeDescCTA = "런처와 관련한 문제가있을경우 관리자에게 문의해주시기 바랍니다"

